export { default as Intro } from './Intro.astro'
export { default as Skills } from './Skills.astro'
export { default as Experiences } from './Experiences.astro'
export { default as Projects } from './Projects.astro'
export { default as Footer } from './Footer.astro'
